### ISSUE TITLE
Blockquote has broken on screenshot 

### ISSUE THREAD

**Issue by orsinium** [oscarmorrison/md-page#10]
See screenshot in readme, blockquote section

<img width="800" alt="sidebyside 2" src="https://user-images.githubusercontent.com/1651212/46540086-ac6d7080-c8fb-11e8-81fe-491898484d53.png">

**Comment by oscarmorrison** [comment]
Yep. Just the screen shot is broken. I fixed this. Will update screen shots soon

**Comment by orsinium** [comment]
Thank you :)

**Comment by oscarmorrison** [comment]
<img width="800" alt="46540086-ac6d7080-c8fb-11e8-81fe-491898484d53" src="https://user-images.githubusercontent.com/1651212/46581049-67247c80-ca7c-11e8-93e2-0327dfea1e74.png">
