### ISSUE TITLE
Clarify the docs

### ISSUE THREAD

**Issue by tunnckoCore** [oscarmorrison/md-page#11]
- "with just markdown"
- "then uses the amazing showdown" markdown converter/parser
- "not a tech savvy"

You need to say that they also need Showdown and need to add it too. Also show that in the example.

**Comment by oscarmorrison** [comment]
Hi @tunnckoCore 

What needs to be clarified?

You add the following line to a `.html` file 

```
<script src="https://cdn.rawgit.com/oscarmorrison/md-page/5833d6d1/md-page.js"></script><noscript>
```

and then write markdown. thats it. Showdown is pre-included in the `md-page.js` script.

**Comment by oscarmorrison** [comment]
Thats not a typo

**Comment by tunnckoCore** [comment]
Hm... There is not opening one.

**Comment by tunnckoCore** [comment]
Oooh... yea yea. Sorry man! :)
