### ISSUE TITLE
Idea: generated navigation tree

### ISSUE THREAD

**Issue by raphaelbastide** [oscarmorrison/md-page#16]
An optional parameter could use a certain title rank (h2 for instance) to generate a navigation tree into a navigation bar:
```
# My website

Welcome to my website

## Cool ideas

- Idea 1
- Idea 2
- Idea 3

## Friends

I love my friends:
- Friend 1
- Friend 2
- Friend 3

## Contacts

Contact me by fax!

```
…would generate:
```
<ul>
  <li><a href="#cool-ideas"></a>Cool ideas</li>
  <li><a href="#friends"></a>Friends</li>
  <li><a href="#Contact"></a>Contact</li>
</ul>
```

This could be nice to have a basic but effective navigation system, able to turn the page into a single page website. What do you think?

**Comment by oscarmorrison** [comment]
Hey @raphaelbastide I quite like the idea. Not sure how it would look, like would that table of contents (that's what I would call it) automatically get added to the top?

Potentially could add a custom mark-down entity something like

```
[Table of Content]
```
And then it would automatically replace that blog with a table of contents created from the markdown?

**Comment by raphaelbastide** [comment]
Yes, the custom markdown entity is a good and flexible idea. Ideally, the generated table of content would have a unique ID in order to customize its style.

**Comment by oscarmorrison** [comment]
Sounds good @raphaelbastide 

Here an example or overriting the custom renderer for markdown: 
https://github.com/oscarmorrison/md-page/blob/master/script.js#L24

And here are the docs https://github.com/showdownjs/showdown/wiki/extensions
You keen to have a go?

**Comment by raphaelbastide** [comment]
I am afraid this is a bit beyound my skills but I am still going to give a try.

**Comment by oscarmorrison** [comment]
Ok. I can help along the way. 

1. Generate your table of contents using some sample markdown.
```
# header one
sometxt
## header two

### header three 
```
etc etc.

this is going to be the trickier part. there is some existing work here: https://github.com/showdownjs/showdown/issues/159

**Comment by oscarmorrison** [comment]
@raphaelbastide let me know if you want to keep this open
