### ISSUE TITLE
Write some tests

### ISSUE THREAD

**Issue by oscarmorrison** [oscarmorrison/md-page#21]
Would be good to have some basics tests in here.

Could just use jest, or something else. Very open to ideas

**Comment by p1ho** [comment]
What kind of tests would you like to run?

If you'd like tests for the functions in [`showdown.js`](https://github.com/oscarmorrison/md-page/blob/master/showdown.js), I personally found [AVA](https://github.com/avajs/ava) the easiest to work with.
If you'd like tests on the rendering of [`index.html`](https://github.com/oscarmorrison/md-page/blob/master/index.html), [Nightwatch.js](https://nightwatchjs.org/) or [Puppeteer](https://github.com/GoogleChrome/puppeteer) could be good options

**Comment by oscarmorrison** [comment]
@p1ho open to anything.
No point testing showdown.js (its external). But something like nightmare js, or a snapshot test to check the rendering of the markdown is always the same when using `md-script.js`

**Comment by p1ho** [comment]
[nightmare.js](https://github.com/segmentio/nightmare) seems promising, even though their builds are failing, it looks like it's due to some permission issue with their repositories and not the actual code.

For the actual tests, we can probably categorize them like this:
1. **HTML rendering**: test that syntax conversion is successful (`#header` --> `<h1 id="header">header</h1>`). If HTML is rendered correctly, we don't have to test behavior (clicking links, etc)
2. **CSS rendering**: test that [basic styles](https://github.com/oscarmorrison/md-page/blob/master/docs/basic_style.md) are properly applied
3. **Custom stuff**: test that stylesheet and title can be customized with the specified syntax

**Comment by IshaTr** [comment]
@oscarmorrison You can just go for snapshot testing, can test for CSS properties through Jest, as it's pretty much stable and pretty easy to catch up with. Also they have a pretty descriptive documentation along with a huge community.
You can refer to the link for knowing all about it:
[Jest Documentation](https://jestjs.io/docs/en/getting-started)

**Comment by Lawrence4code** [comment]
@IshaTr @oscarmorrison, Jest is great option for testing, if guys decide on it, do let me know. I'd be happy to contribute.

**Comment by oscarmorrison** [comment]
@p1ho @IshaTr @Lawrence4code PR welcome. Happy for jest & jest snapshot

**Comment by p1ho** [comment]
I'd be happy to use jest & jest snapshot as well.

**Comment by jorgeruvalcaba** [comment]
@IshaTr @Lawrence4code have you guys made any progress here? would like to contribute to this issue

**Comment by oscarmorrison** [comment]
@jorgeruvalcaba Don't think there is any progress that I know about. Green field on the testing front

**Comment by dhuang612** [comment]
Hi guys,

Please let me know if I can help out with this

**Comment by p1ho** [comment]
There was a recent effort to create automated test/build workflows #42 
We will be using jest and all the test files will be inside `./test` folder.
I would say feel free to go ahead and create some tests, but don't make PR yet until #42 is reviewed and merged.

**Comment by iTrauco** [comment]
I would love to help on this

**Comment by p1ho** [comment]
#42 has been merged.
new tests can be added to [`/test/script.test.js`](https://github.com/oscarmorrison/md-page/blob/review/test/script.test.js) (right now it's just a dummy test)

**Comment by Leomedina** [comment]
Hi! I'm a new developer and would love the chance to help on this

**Comment by oscarmorrison** [comment]
Awesome @Leomedina 

test away!

**Comment by Leomedina** [comment]
Great! Thank you @oscarmorrison, mind assigning the issue my way? Once assigned, I'll open a PR. Thanks!

**Comment by oscarmorrison** [comment]
Done

**Comment by Leomedina** [comment]
Gracias! I'm shooting to complete the HTML render tests by end of next week :)

**Comment by Leomedina** [comment]
Submitted PR request for HTML Renders #52 ! Let me know if you have any questions
