### ISSUE TITLE
Add some more documentation

### ISSUE THREAD

**Issue by oscarmorrison** [oscarmorrison/md-page#22]
Current wiki is pretty bare, would be good to have some more detailed examples.

- with custom styles
- with html elements
- etc

**Comment by nic-og** [comment]
I'd like to work on it.

**Comment by oscarmorrison** [comment]
Hi @nic-og would really appreciate any help. 
I have moved the wiki to https://github.com/oscarmorrison/md-page/tree/master/docs
so that you can work on it and do a [pull request](https://yangsu.github.io/pull-request-tutorial/) 

**Let me know if you need any help or have any questions**

Would be good to add some extra pages, and then some examples:
- Basic example
- Example with custom style
- Example with custom title
- Example with custom js
