### ISSUE TITLE
Add max-width to minimal CSS in the spirit of "better/perfect motherf***g website"

### ISSUE THREAD

**Issue by Offirmo** [oscarmorrison/md-page#23]
Hi! I understand and perfectly agree that the CSS should stay minimal.

However, by default, having a max-width would be nice.

May I suggest, if you don't know them:
* http://motherfuckingwebsite.com/
* http://bettermotherfuckingwebsite.com/
* http://perfectmotherfuckingwebsite.com/

**Comment by oscarmorrison** [comment]
Hey @Offirmo What exactly are you suggesting?

Can just add a style tag in a head tag at the top with any custom css you would like, is that enough?

**Comment by oscarmorrison** [comment]
Closing this issue as I haven't heard from @Offirmo.
