### ISSUE TITLE
Complex anchor rendered incorrectly

### ISSUE THREAD

**Issue by szepeviktor** [oscarmorrison/md-page#25]
```
- [UpCloud ⌛](http://status.upcloud.com/) | [Cogent :airplane:](http://status.cogentco.com/)
```

redered as 

- [Cogent :airplane:](http://status.cogentco.com/)

Please advise.
Thank you.

**Comment by oscarmorrison** [comment]
Can you try it here http://demo.showdownjs.com

**Comment by szepeviktor** [comment]
Thanks, it work on that site.
How come it does not work on mine?

**Comment by szepeviktor** [comment]
@oscarmorrison How about changing to `regex: /<a\shref[^>]+">/g,` ?

**Comment by oscarmorrison** [comment]
Pr welcome

**Comment by szepeviktor** [comment]
Sent! See #26
