### ISSUE TITLE
Why is the js all one one line?

### ISSUE THREAD

**Issue by chicks-net** [oscarmorrison/md-page#3]
It is hard to eye-ball this way.

**Comment by adriennn** [comment]
look at makefile.

**Comment by oscarmorrison** [comment]
Hey @chicks-net its been minified and compress to save space on peoples browsers (here some more information on the why https://developers.google.com/speed/docs/insights/MinifyResources)

If you want to see what's going on just look at https://github.com/oscarmorrison/md-page/blob/master/script.js
