### ISSUE TITLE
Add Russian language

### ISSUE THREAD

**Issue by owner** [oscarmorrison/md-page#30]
![header - mozilla firefox 2018-12-08 01 38 04](https://user-images.githubusercontent.com/24358937/49676254-00c2d700-fa8a-11e8-9feb-2125e9ce34e9.png)

**Comment by oscarmorrison** [comment]
Would you be interested in doing a PR @owner

**Comment by owner** [comment]
I can help you, but "how to"?

**Comment by shdq** [comment]
I checked and it works in Russian, maybe @owner saved html file in non-UTF8 encoding?

**Comment by owner** [comment]
@shdq, yeah. Works. Close issue, pls.
