### ISSUE TITLE
Border (width) for webpage

### ISSUE THREAD

**Issue by owner** [oscarmorrison/md-page#31]
![mozilla firefox 2018-12-08 01 42 39](https://user-images.githubusercontent.com/24358937/49676508-11278180-fa8b-11e8-8b18-ca8f59275f2f.png)

**Comment by oscarmorrison** [comment]
Hi Can you please give some more information about this issue?

**Comment by owner** [comment]
Do you setup a limit for width at markdown pages? Text located at full width page, but if i have 21:9 monitor, its very hardly for readers.

**Comment by owner** [comment]
`padding: 150;
padding-top: 50;`

**Comment by oscarmorrison** [comment]
Hi you can add this custom css to your's on a case by case basis
