### ISSUE TITLE
Syntax highlight for inline code does not work

### ISSUE THREAD

**Issue by UmutAlihan** [oscarmorrison/md-page#32]
First of all, thank you very much for such contribution to community!

Here when I try to write powershell code with syntax highlighting, it fails.

Markdown:
![resim](https://user-images.githubusercontent.com/16688836/51298628-4e8e1000-1a36-11e9-8eb2-ae4235f05504.png)

Expected:
```PowerShell
function Is-WindowAvailable {
    param(
        [string]$QueryProcess,
        [string]$WindowTitle
    )
```

Result:
![resim](https://user-images.githubusercontent.com/16688836/51298589-269eac80-1a36-11e9-9e68-aa39c4fbee7d.png)

**Comment by oscarmorrison** [comment]
PR Welcome

**Comment by UmutAlihan** [comment]
I have fixed it by using:

 {%highlighter Powershell %} 
 (some code)
{% endhiglight %}

instead of:
```Powershell
(some code)
```


This is actually not a fix, instead a workaround. Since I use jekyll to generate site, this {% %} syntax had additional highlighting feature. So I used it instead of makrkdown.

I think we can close it :)
Cheers,
