### ISSUE TITLE
Question about setting up dev

### ISSUE THREAD

**Issue by p1ho** [oscarmorrison/md-page#36]
Hello,

I have a question about [`DEV_README`](https://github.com/oscarmorrison/md-page/blob/master/DEV_README.md)
I understand `uglify-js` is needed to compile the js files you have, but I'm unsure what `make` is referring to. Is this related to the `Makefile` ?
I got the build process to run using the command `./Makefile` on Git Bash on Windows 10, but I can't specify whether I want to run `concat` or `setup`.

**Comment by oscarmorrison** [comment]
Hey @p1ho I have updated readme docs https://github.com/oscarmorrison/md-page/blob/master/DEV_README.md

make file is just to save the concat and install

`make setup`

`make concat`
