### ISSUE TITLE
Can i use md-page in IE11 ?

### ISSUE THREAD

**Issue by ji-ryoo** [oscarmorrison/md-page#43]
hello.

I use md-page a lot because it's very convenient.

When i use IE11, md page does not work.
Some users are still using IE...

Is there a way to get md-page working in IE ?

**Comment by ji-ryoo** [comment]
Get error: SCRIPT438: Object doesn't support property or method 'prepend' in IE11
I have no choice but to write code without using the prepend function. ..

**Comment by p1ho** [comment]
Ah, it's because of [PR 37](https://github.com/oscarmorrison/md-page/pull/37) (I opened this a while back)
I'm not sure if @oscarmorrison is still maintaining this project, but you should open a PR if you found a fix (Otherwise, you can probably just use your own fork)!

**Comment by p1ho** [comment]
@ji-ryoo This is still an ongoing issue, we can move this discussion to #45
