### ISSUE TITLE
Implementing SSR will really perfect the utility of this project. [Video Included]

### ISSUE THREAD

**Issue by jimmylee** [oscarmorrison/md-page#5]
**This is really cool! Nice work :-)**

I've highlighted an issue I experienced looking at your current demo. See below:

![3](https://user-images.githubusercontent.com/310223/46574901-dfe1e680-c95f-11e8-93a1-ea868238c943.gif)

### What is the problem?
Flash of unformatted text.

### Some ideas

* Try server side rendering to generate the DOM in advance.
* **Hack** - maybe you can use some CSS + JS to prevent the flash of styleless text.

I hope this helps you! Nice use of [Showdown](https://github.com/showdownjs/showdown).

**Comment by oscarmorrison** [comment]
Hey @jimmylee thanks for the feedback. Def notice the FOUC. Opened #8 to deal with this, likely going to have to do something with your second suggestions css hack.

there's heaps of existing server side rendering options out there, so not the intentions of this project, see here for a bit more context https://github.com/oscarmorrison/md-page/wiki#why)
