### ISSUE TITLE
small grammatical mistakes in Readme.md

### ISSUE THREAD

**Issue by code-reaper08** [oscarmorrison/md-page#53]
Hey there !
I found some small grammatical typos [here](https://github.com/oscarmorrison/md-page/blob/review/docs/README.md).

Would you mind assigning this to me, so that I can come up with a PR.

**Comment by oscarmorrison** [comment]
Hey @code-reaper08 

<img width="1202" alt="image" src="https://user-images.githubusercontent.com/1651212/111923017-412aaf80-8af1-11eb-8044-73f3fd609fba.png">

Click the edit, and make your edits, and open a PR.

**Comment by code-reaper08** [comment]
> Hey @code-reaper08
> 
> <img alt="image" width="1202" src="https://user-images.githubusercontent.com/1651212/111923017-412aaf80-8af1-11eb-8044-73f3fd609fba.png">
> 
> Click the edit, and make your edits, and open a PR.

Hey @oscarmorrison 😁
Thanks for assigning , will create a PR soon.

**Comment by petedussin** [comment]
This is really neat. What a great little idea!

**Comment by a12baghel2** [comment]
Hey @oscarmorrison , I have fixed the grammatical error and typos please review my PR #56  and merge.
