### ISSUE TITLE
French accent issue

### ISSUE THREAD

**Issue by jgwill** [oscarmorrison/md-page#57]
Hi
So far, very useful.  I was wondering if the french accent issue you can see in the image can be fixed with ease :) ?
regards

![image](https://user-images.githubusercontent.com/23141173/168458421-a485c73b-3a37-4e96-af8b-93507d7d1d5e.png)

**Comment by oscarmorrison** [comment]
PRs welcome

**Comment by benjaminwiseboy** [comment]
Hello, I'm new to Open source. How can I contribute to this topic ?

**Comment by oscarmorrison** [comment]
https://www.freecodecamp.org/news/how-to-contribute-to-open-source-projects-beginners-guide/

**Comment by heyallan** [comment]
What is the character that is failing?
How to reproduce?

**Comment by adsuth** [comment]
> What is the character that is failing? How to reproduce?

Based on context, probably a C-Cedilla ( ç ).

Having trouble reproducing the problem, seems to process them fine for me.
Has this been patched?

![image](https://user-images.githubusercontent.com/74009107/188493066-43e5c7a3-4795-4316-b6fd-3c499a341da2.png)

**Comment by StefanoCappellini** [comment]
It's a matter of content type encoding. Its server [see here](https://guillaumeisabelle.com/conditionsacheteurs-en/) doesn't specify any content encoding within the Content-Type header. The browser start searching for the meta tag - that's simply not there, being generated afterwards - reverting to default content type.
Possible solutions (I'm not an expert of md-page):

- Setting the charset encoding directly from Apache (wise)
- Putting the JS and the Markdown inside an html template that pre-defines the charset meta tag (it should work without duplicates, am I correct?)

**Comment by StefanoCappellini** [comment]
I've just set up a small demo:
- With content-type charset: [http://tests.codingwh.com/md-page-accent/](http://tests.codingwh.com/md-page-accent/)
- Without: [http://tests.codingwh.com/md-page-accent/without](http://tests.codingwh.com/md-page-accent/without)

It happens, obviously, if the default of the browser is different from utf8 :D

**Comment by oscarmorrison** [comment]
See: https://github.com/oscarmorrison/md-page/blob/main/docs/common_problems.md
