### ISSUE TITLE
Cloudflare's rocket

### ISSUE THREAD

**Issue by szepeviktor** [oscarmorrison/md-page#6]
Please consider disabling Rocket loader on oscarmorrison.com/md-page
I makes a big FOUC.

**Comment by oscarmorrison** [comment]
Thanks @szepeviktor this fixed it, just added a page rule

<img width="844" alt="image" src="https://user-images.githubusercontent.com/1651212/46576428-d2d2ff00-ca14-11e8-9f03-5617a1ae250f.png">

**Comment by szepeviktor** [comment]
You're welcome.
