### ISSUE TITLE
npm run test fails: 18 snapshots failed.

### ISSUE THREAD

**Issue by IvaniGabrovsky** [oscarmorrison/md-page#60]
When I run npm run test I am getting the following error: 
...
`● HTML Rendering Tests: Ensures Blockquotes are rendered accurately › It should render multiple-line blockquotes

    expect(received).toMatchSnapshot()

    Snapshot name: `HTML Rendering Tests: Ensures Blockquotes are rendered accurately It should render multiple-line blockquotes 1`

    Snapshot: "<blockquote>
      <p>Line 1<br>
      Line 2<br>
      Line 3</p>
    </blockquote>"
    Received: ""

      207 |     await dom.window.document.addEventListener('DOMContentLoaded', async () => {
      208 |       await setImmediate(() => { }); // This is required for the second DOMContentLoaded.
    > 209 |       expect(dom.window.document.body.innerHTML).toMatchSnapshot();
          |                                                  ^
      210 |       done();
      211 |     });
      212 |   });

      at Document.<anonymous> (test/script.test.js:209:50)

 › 18 snapshots failed.
Snapshot Summary
 › 18 snapshots failed from 1 test suite. Inspect your code changes or press `u` to update them.

Test Suites: 1 failed, 1 total
Tests:       18 failed, 18 total
Snapshots:   18 failed, 18 total
`

**Comment by IvaniGabrovsky** [comment]
I am going update the snapshots and open a pr.

**Comment by oscarmorrison** [comment]
Thanks @IvaniGabrovsky
