### ISSUE TITLE
md-page.js is gone

### ISSUE THREAD

**Issue by tyeeman** [oscarmorrison/md-page#64]
Not found as of Dec 7 2023

**Comment by florianfesti** [comment]
Looks like if got removed/no longer built with #42 After 3 and a half years it has finally fallen out of rawcdn. As even the Readme still promotes this URL it should either be re-created in this repo or at least update the instructions to use the files in src/ if this is possible

**Comment by oscarmorrison** [comment]
@p1ho any chance you can please have a look at this, seems to be an issue from the automation

**Comment by oscarmorrison** [comment]
Closed by #68
