### ISSUE TITLE
GitHub-like style

### ISSUE THREAD

**Issue by szepeviktor** [oscarmorrison/md-page#7]
Could you add `<body class="markdown-body">` to support https://github.com/sindresorhus/github-markdown-css ?

**Comment by oscarmorrison** [comment]
I purposely don't want to include a style sheet with this, and [scripts.js](https://github.com/oscarmorrison/md-page/blob/master/script.js) has all the styling I want to included. But you still have a couple of options:

1. add a header and a style tag to your page, and wrap your markdown in a body tag with that class
2. fork the repo, do whatever you like

**Comment by szepeviktor** [comment]
Thank you.
`document.body.className = "markdown-body";`

**Comment by irvnriir** [comment]
> `document.body.className = "markdown-body";`

@szepeviktor can you please clarify how you implemented this line ?

**Comment by szepeviktor** [comment]
Hello @irvnriir!
I'm not a developer. I was just playing with this project.

As far as I remember I was inserting `document.body.className = "markdown-body";` and the CSS file of https://github.com/sindresorhus/github-markdown-css into the HTML.

**Comment by irvnriir** [comment]
Seems that this line wasn't really needed .

This .html works
```
<!DOCTYPE html><html><head><meta charset="utf-8">

<title>__textLine</title>

<link rel="stylesheet" href="assets/github-markdown-dark.css">

<script src="assets/md-page_f.js"></script>

</head><body class="markdown-body">
<noscript>

__markdownText

</noscript>
</body></html>
```
